services:
    app:
        build: .
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - /var/www/vendor
        environment:
            APP_KEY: base64:BN0xJ3SYWR+5Re2I+W5rN7tFwP6hd6WyNMcNs2zMIEg=
            APP_ENV: local
            APP_DEBUG: "true"
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: project-db
            DB_USERNAME: admin
            DB_PASSWORD: password
        depends_on:
            - db
        networks:
            - laravel
        command: sh -c "php artisan migrate --force && php-fpm"

    nginx:
        image: nginx:1.25
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:16
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: project-db
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

volumes:
    postgres_data:

networks:
    laravel:
        driver: bridge
